// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var EventEmitter$NodeJs = require("../../src/EventEmitter.bs.js");

EventEmitter$NodeJs.Make({});

var uniqueSymbol = (Symbol("emitter1"));

var Events = {
  symbol: uniqueSymbol,
  text: "text",
  integer: "integer"
};

var Emitter1 = {
  uniqueSymbol: uniqueSymbol,
  Events: Events
};

exports.Emitter1 = Emitter1;
/*  Not a pure module */
