// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Nodestream = require("node:stream");

function makeReadableEmpty(param) {
  return new Nodestream.Readable({
              objectMode: false,
              autoDestroy: true,
              destroy: (function (error, callback) {
                  Curry._1(callback, (error == null) ? undefined : Caml_option.some(error));
                }),
              read: (function (param) {
                  
                })
            });
}

function makeWritableEmpty(param) {
  return new Nodestream.Writable({
              objectMode: false,
              autoDestroy: true,
              destroy: (function (error, callback) {
                  Curry._1(callback, (error == null) ? undefined : Caml_option.some(error));
                }),
              write: (function (param, param$1, callback) {
                  Curry._1(callback, undefined);
                })
            });
}

exports.makeReadableEmpty = makeReadableEmpty;
exports.makeWritableEmpty = makeWritableEmpty;
/* node:stream Not a pure module */
