// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Stream = require("stream");
var Caml_option = require("rescript/lib/js/caml_option.js");

function makeReadableEmpty(param) {
  return new Stream.Readable({
              objectMode: false,
              autoDestroy: true,
              destroy: (function (error, callback) {
                  return Curry._1(callback, (error == null) ? undefined : Caml_option.some(error));
                }),
              read: (function (param) {
                  
                })
            });
}

function makeWritableEmpty(param) {
  return new Stream.Writable({
              objectMode: false,
              autoDestroy: true,
              destroy: (function (error, callback) {
                  return Curry._1(callback, (error == null) ? undefined : Caml_option.some(error));
                }),
              write: (function (param, param$1, callback) {
                  return Curry._1(callback, undefined);
                })
            });
}

exports.makeReadableEmpty = makeReadableEmpty;
exports.makeWritableEmpty = makeWritableEmpty;
/* stream Not a pure module */
