// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Process = require("process");
var Nodereadline = require("node:readline");

Nodereadline.clearLine(Process.stdout, 1, (function (param) {
        console.log("line cleared");
      }));

Nodereadline.clearScreenDown(Process.stdout, (function (param) {
        console.log("screen cleared");
      }));

Nodereadline.cursorTo(Process.stdout, 1, 2, (function (param) {
        console.log("cursor to");
      }));

Nodereadline.moveCursor(Process.stdout, 1, 2, (function (param) {
        console.log("cursor moved");
      }));

/*  Not a pure module */
