// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function instanceOfClass(instance, _class) {
  try {
    return (instance instanceof _class);
  } catch {
    return false;
  }
}
;

function instanceOfClass$1(instance, class_) {
  return instanceOfClass(instance, class_);
}

exports.instanceOfClass = instanceOfClass$1;
/*  Not a pure module */
