// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Zora = require("@dusty-phillips/rescript-zora/lib/js/src/Zora.bs.js");
var Zora$1 = require("zora");
var Js_string = require("rescript/lib/js/js_string.js");

Zora$1.test("Fs", (function (t) {
        t.test("readFile should read entire file", (function (t) {
                return Zora.then(Zora.then(Fs.promises.open(__filename, "r"), (function (fh) {
                                  return Zora.then(fh.readFile(), (function (buffer) {
                                                return Zora.then(fh.close(), (function (param) {
                                                              return Zora.done(buffer);
                                                            }));
                                              }));
                                })), (function (buffer) {
                              t.ok(buffer.indexOf("Random string: Gh2e71pdHhPxU") > 1, "buffer index was not greater than zero");
                              return Zora.done(undefined);
                            }));
              }));
        t.test("readFileWith should read entire file as a string", (function (t) {
                return Zora.then(Zora.then(Fs.promises.open(__filename, "r"), (function (fh) {
                                  return Zora.then(fh.readFile({
                                                  encoding: "UTF-8"
                                                }), (function (buffer) {
                                                return Zora.then(fh.close(), (function (param) {
                                                              return Zora.done(buffer);
                                                            }));
                                              }));
                                })), (function (content) {
                              t.ok(Js_string.indexOf("Random string: uCF6c5f3Arrq", content) > 0, "buffer string indexOf was not greater than zero");
                              return Zora.done(undefined);
                            }));
              }));
        return Zora.done(undefined);
      }));

/*  Not a pure module */
