// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Zora = require("zora");
var Js_string = require("rescript/lib/js/js_string.js");

Zora.test("Fs", (async function (t) {
        t.test("readFile should read entire file", (async function (t) {
                var fh = await Fs.promises.open(__filename, "r");
                var buffer = await fh.readFile();
                await fh.close();
                t.ok(buffer.indexOf("Random string: Gh2e71pdHhPxU") > 1, "buffer index was not greater than zero");
              }));
        t.test("readFileWith should read entire file as a string", (async function (t) {
                var fh = await Fs.promises.open(__filename, "r");
                var buffer = await fh.readFile({
                      encoding: "UTF-8"
                    });
                await fh.close();
                t.ok(Js_string.indexOf("Random string: uCF6c5f3Arrq", buffer) > 0, "buffer string indexOf was not greater than zero");
              }));
      }));

/*  Not a pure module */
