// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");

Zora.test("Global", (function (t) {
        t.test("dirname should be defined", (function (t) {
                t.notEqual(__dirname, undefined, "");
              }));
        t.test("dirname should be of type 'string'", (function (t) {
                t.equal(typeof __dirname, "string", "");
              }));
        t.test("filename should be defined", (function (t) {
                t.notEqual(__filename, undefined, "");
              }));
        t.test("filename should be of type 'string'", (function (t) {
                t.equal(typeof __filename, "string", "");
              }));
        t.test("'global object' should be defined", (function (t) {
                t.notEqual(global, undefined, "");
              }));
        t.test("'global' object should be of type 'object'", (function (t) {
                t.equal(typeof global, "object", "");
              }));
        t.test("'require' function should be defined", (function (t) {
                t.notEqual((function (prim) {
                        return require(prim);
                      }), undefined, "");
              }));
        t.test("'require' function should be defined", (function (t) {
                t.equal(typeof (function (prim) {
                        return require(prim);
                      }), "function", "");
              }));
        t.test("'require' fuction should return a defined value from a relative path", (function (t) {
                t.notEqual(require("path"), undefined, "");
              }));
        t.test("'require' fuction should successfully import a module object from a relative path", (function (t) {
                t.equal(typeof require("path"), "object", "");
              }));
      }));

/*  Not a pure module */
