// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");
var Nodepath = require("node:path");

Zora.test("Path", (function (t) {
        t.test("basename should isolate filename with extension", (function (t) {
                t.equal(Nodepath.posix.basename("/tmp/myfile.html"), "myfile.html", "");
              }));
      }));

/*  Not a pure module */
