// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");
var Zora = require("zora");

Zora.test("Path", (function (t) {
        t.test("basename should isolate filename with extension", (function (t) {
                t.equal(Path.posix.basename("/tmp/myfile.html"), "myfile.html", "");
                
              }));
        
      }));

/*  Not a pure module */
