// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");
var Promises = require("node:timers/promises");

Zora.test("Timers (promises)", (async function (t) {
        t.test("setTimeout", (async function (t) {
                await Promises.setTimeout(100);
                t.ok(true, "");
              }));
        t.test("setImmediate", (async function (t) {
                var yes = await Promises.setImmediate("yes");
                t.equal(yes, "yes", "");
              }));
      }));

/*  Not a pure module */
