// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");
var Nodeutil = require("node:util");

Zora.test("Util.Types", (function (t) {
        t.test("Util.Types.isAnyArrayBuffer(arrayBuffer) should return true", (function (t) {
                var arrayBuffer = new ArrayBuffer(16);
                t.equal(Nodeutil.types.isAnyArrayBuffer(arrayBuffer), true, "");
              }));
        t.test("Util.Types.isAnyArrayBuffer(string) should return false", (function (t) {
                t.equal(Nodeutil.types.isAnyArrayBuffer("not array buffer"), false, "");
              }));
      }));

/*  Not a pure module */
