// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Util = require("util");
var Zora = require("zora");

Zora.test("Util.Types", (function (t) {
        t.test("Util.Types.isAnyArrayBuffer(arrayBuffer) should return true", (function (t) {
                var arrayBuffer = new ArrayBuffer(16);
                t.equal(Util.types.isAnyArrayBuffer(arrayBuffer), true, "");
                
              }));
        t.test("Util.Types.isAnyArrayBuffer(string) should return false", (function (t) {
                t.equal(Util.types.isAnyArrayBuffer("not array buffer"), false, "");
                
              }));
        
      }));

/*  Not a pure module */
