// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Impl(T) {
  return {};
}

function Make($star) {
  return {};
}

exports.Impl = Impl;
exports.Make = Make;
/* No side effect */
