// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Tls$NodeJs = require("./Tls.bs.js");

var Events = {};

var Impl = {};

var HttpsServer = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Agent = {
  Events: Events$1
};

exports.HttpsServer = HttpsServer;
exports.Agent = Agent;
/* Tls-NodeJs Not a pure module */
