// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Net$NodeJs = require("./Net.bs.js");

var Events = {};

var Impl = {};

var IncomingMessage = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Impl$1 = {};

var ClientRequest = {
  Events: Events$1,
  Impl: Impl$1
};

var Events$2 = {};

var Impl$2 = {};

var ServerResponse = {
  Events: Events$2,
  Impl: Impl$2
};

var Agent = {};

var Events$3 = {};

var Impl$3 = {};

var Server = {
  Events: Events$3,
  Impl: Impl$3
};

exports.IncomingMessage = IncomingMessage;
exports.ClientRequest = ClientRequest;
exports.ServerResponse = ServerResponse;
exports.Agent = Agent;
exports.Server = Server;
/* Net-NodeJs Not a pure module */
