// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Events = {};

var Impl = {};

var Common = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Impl$1 = {};

var Writable = {
  Events: Events$1,
  Impl: Impl$1
};

var Events$2 = {};

var Impl$2 = {};

var Readable = {
  Events: Events$2,
  Impl: Impl$2
};

var Events$3 = {};

var Impl$3 = {};

var Duplex = {
  Events: Events$3,
  Impl: Impl$3
};

var Events$4 = {};

var Impl$4 = {};

var Transform = {
  Events: Events$4,
  Impl: Impl$4
};

var Events$5 = {};

var Impl$5 = {};

var PassThrough = {
  Events: Events$5,
  Impl: Impl$5
};

var Events$6 = {};

exports.Common = Common;
exports.Writable = Writable;
exports.Readable = Readable;
exports.Duplex = Duplex;
exports.Transform = Transform;
exports.PassThrough = PassThrough;
exports.Events = Events$6;
/* No side effect */
