// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("rescript/lib/js/pervasives.js");

function classifyOpt(value) {
  if (typeof value === "string") {
    return {
            TAG: /* String */0,
            _0: value
          };
  } else if (Buffer.isBuffer(value)) {
    return {
            TAG: /* Buffer */1,
            _0: value
          };
  } else {
    return ;
  }
}

function classifyExn(value) {
  if (typeof value === "string") {
    return {
            TAG: /* String */0,
            _0: value
          };
  } else if (Buffer.isBuffer(value)) {
    return {
            TAG: /* Buffer */1,
            _0: value
          };
  } else {
    return Pervasives.failwith("Unknown data type");
  }
}

function classify(value) {
  if (typeof value === "string") {
    return {
            TAG: /* Ok */0,
            _0: {
              TAG: /* String */0,
              _0: value
            }
          };
  } else if (Buffer.isBuffer(value)) {
    return {
            TAG: /* Ok */0,
            _0: {
              TAG: /* Buffer */1,
              _0: value
            }
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: value
          };
  }
}

exports.classifyOpt = classifyOpt;
exports.classifyExn = classifyExn;
exports.classify = classify;
/* No side effect */
