// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var PervasivesU = require("rescript/lib/js/pervasivesU.js");

function classifyOpt(value) {
  if (typeof value === "string") {
    return {
            TAG: "String",
            _0: value
          };
  } else if (Buffer.isBuffer(value)) {
    return {
            TAG: "Buffer",
            _0: value
          };
  } else {
    return ;
  }
}

function classifyExn(value) {
  if (typeof value === "string") {
    return {
            TAG: "String",
            _0: value
          };
  } else if (Buffer.isBuffer(value)) {
    return {
            TAG: "Buffer",
            _0: value
          };
  } else {
    return PervasivesU.failwith("Unknown data type");
  }
}

function classify(value) {
  if (typeof value === "string") {
    return {
            TAG: "Ok",
            _0: {
              TAG: "String",
              _0: value
            }
          };
  } else if (Buffer.isBuffer(value)) {
    return {
            TAG: "Ok",
            _0: {
              TAG: "Buffer",
              _0: value
            }
          };
  } else {
    return {
            TAG: "Error",
            _0: value
          };
  }
}

exports.classifyOpt = classifyOpt;
exports.classifyExn = classifyExn;
exports.classify = classify;
/* No side effect */
