// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Immediate = {};

var Timeout = {};

var Promises = {};

exports.Immediate = Immediate;
exports.Timeout = Timeout;
exports.Promises = Promises;
/* No side effect */
