// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Net$NodeJs = require("./Net.bs.js");

var Events = {};

var Impl = {};

var TlsSocket = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Impl$1 = {};

var TlsServer = {
  Events: Events$1,
  Impl: Impl$1
};

exports.TlsSocket = TlsSocket;
exports.TlsServer = TlsServer;
/* Net-NodeJs Not a pure module */
