// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Events = {};

var Impl = {};

var ReadStream = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Impl$1 = {};

var WriteStream = {
  Events: Events$1,
  Impl: Impl$1
};

exports.ReadStream = ReadStream;
exports.WriteStream = WriteStream;
/* No side effect */
