// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nodeurl = require("node:url");
var Js_null_undefined = require("rescript/lib/js/js_null_undefined.js");

var SearchParams = {};

function format(auth, fragment, search, unicode, url) {
  return Nodeurl.format(url, {
              auth: Js_null_undefined.fromOption(auth),
              fragment: Js_null_undefined.fromOption(fragment),
              search: Js_null_undefined.fromOption(search),
              unicode: Js_null_undefined.fromOption(unicode)
            });
}

exports.SearchParams = SearchParams;
exports.format = format;
/* node:url Not a pure module */
