// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function WithMessageType(T) {
  return {};
}

var $$MessagePort = {
  WithMessageType: WithMessageType
};

function WithMessageTypes(T) {
  return {};
}

var $$MessageChannel = {
  WithMessageTypes: WithMessageTypes
};

function WithMessageType$1(T) {
  return {};
}

var $$Worker = {
  WithMessageType: WithMessageType$1
};

function WithMessageType$2(T) {
  var $$Worker = {};
  return {
          $$Worker: $$Worker
        };
}

exports.$$MessagePort = $$MessagePort;
exports.$$MessageChannel = $$MessageChannel;
exports.$$Worker = $$Worker;
exports.WithMessageType = WithMessageType$2;
/* No side effect */
