// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Readline = require("readline");
var Pervasives = require("rescript/lib/js/pervasives.js");

var rl = Readline.createInterface({
      input: Fs.createReadStream("sample.txt"),
      crlfDelay: Pervasives.infinity
    });

rl.on("line", (function (line) {
        console.log("Received: " + line + "");
      }));

exports.rl = rl;
/* rl Not a pure module */
