// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nodefs = require("node:fs");
var PervasivesU = require("rescript/lib/js/pervasivesU.js");
var Nodereadline = require("node:readline");

var rl = Nodereadline.createInterface({
      input: Nodefs.createReadStream("sample.txt"),
      crlfDelay: PervasivesU.infinity
    });

rl.on("line", (function (line) {
        console.log("Received: " + line);
      }));

exports.rl = rl;
/* rl Not a pure module */
