// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nodefs = require("node:fs");
var Process = require("process");
var Nodepath = require("node:path");

var data = Buffer.from("Sample text to write to a file!");

var $$process = Process;

var outputPath = Nodepath.relative($$process.cwd(), "example__output.txt");

var writeStream = Nodefs.createWriteStream(outputPath);

function logErrorIfExists(maybeError) {
  if (!(maybeError == null)) {
    console.log("An error occurred", maybeError);
    return ;
  }
  
}

writeStream.write(data, (function (maybeError) {
        logErrorIfExists(maybeError);
        console.log("Finished");
      }));

exports.data = data;
exports.$$process = $$process;
exports.outputPath = outputPath;
exports.writeStream = writeStream;
exports.logErrorIfExists = logErrorIfExists;
/* data Not a pure module */
