// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var Process = require("process");

var data = Buffer.from("Sample text to write to a file!");

var $$process = Process;

var outputPath = Path.relative($$process.cwd(), "example__output.txt");

var writeStream = Fs.createWriteStream(outputPath);

function logErrorIfExists(maybeError) {
  if (!(maybeError == null)) {
    console.log("An error occurred", maybeError);
    return ;
  }
  
}

writeStream.write(data, (function (maybeError) {
        logErrorIfExists(maybeError);
        console.log("Finished");
      }));

exports.data = data;
exports.$$process = $$process;
exports.outputPath = outputPath;
exports.writeStream = writeStream;
exports.logErrorIfExists = logErrorIfExists;
/* data Not a pure module */
